name: Docker CI

on:
  push:
    branches:
      - master

env:
  image: ${{ secrets.DOCKERHUB_USERNAME }}/monthly-expenses

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: |
          echo "version=$(cat app/env_variables.py| grep "VERSION =" | egrep -o "[0-9.]{1,}")" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build & Push Image amd64
        run: |
          docker buildx build --push --platform linux/amd64 -t ${{ env.image }}:amd64-latest -t ${{ env.image }}:amd64-${{env.version}} .
      - name: Build & Push Image arm64
        run: |
          docker buildx build --push --platform linux/arm64  -t ${{ env.image }}:arm64v8-latest -t ${{ env.image }}:arm64v8-${{env.version}} -f ./Dockerfile.aarch64 .

      - name: Merge images
        run: |
          docker buildx imagetools create -t ${{ env.image }}:latest ${{ env.image }}:amd64-latest ${{ env.image }}:arm64v8-latest
          docker buildx imagetools create -t ${{ env.image }}:${{env.version}} ${{ env.image }}:amd64-${{env.version}} ${{ env.image }}:arm64v8-${{env.version}}
